apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-proxmox
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`proxmox.local.yourdomain.com`)
      kind: Rule
      services:
        - name: service-proxmox
          port: 443
          serversTransport: proxmox-insecure
      middlewares:
        - name: default-headers
  tls:
    secretName: wildcard-yourdomain-tls
