apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-mikrotik
  namespace: default
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`switch.local.yourdomain.com`)
      kind: Rule
      services:
        - name: service-switch
          port: 80
          serversTransport: switch-insecure  # Use the transport
      middlewares:
        - name: default-headers
  tls:
    secretName: wildcard-yourdomain-tls
