apiVersion: v1
kind: Service
metadata:
  name: blocky
  namespace: blocky
spec:
  selector:
    app: blocky
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: http
      port: 4000
      protocol: TCP
      targetPort: 4000
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: <change to real ip address>
