apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: apt-cacher-ng
  namespace: apt-cacher-ng
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`cache.local.yourdomain.com`)
      kind: Rule
      services:
        - name: apt-cacher-ng
          port: 3142
      middlewares:
        - name: default-headers
  tls:
    secretName: cache-yourdomain-tls
