apiVersion: v1
kind: Service
metadata:
  name: apt-cacher-ng
  namespace: apt-cacher-ng
spec:
  selector:
    app: apt-cacher-ng
  ports:
    - name: http
      protocol: TCP
      port: 3142
      targetPort: 3142
  type: LoadBalancer
  loadBalancerIP: <fill in some ip address here>
